# .deepsource.toml
version = 1

# Test dosyalarını işaretle (bazı kurallar testlerde gürültü yapmasın)
test_patterns = [
  "tests/**"
]

# Gürültü / üretilmiş dizinleri dışla
exclude_patterns = [
  "**/node_modules/**",
  "**/__pycache__/**",
  ".venv/**",
  "venv/**",
  "alembic/versions/**",
  "data/**",
  "butt_background/**",
  # Minify/derlenmiş varlıkları da istersen ekleyebilirsin:
  "static/**/*.min.*"
]

# --- Analizörler ---

[[analyzers]]
name = "python"
enabled = true
  [analyzers.meta]
  runtime_version = "3.x.x"           # Proje 3.11 kullanıyorsa; değilse 3.x yap
  # Gerekiyorsa bağımlılık dosyalarını belirt:
  dependency_file_paths = ["requirements.txt"]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"     # Anahtar/şifre sızıntısı taraması
enabled = true

# --- Otomatik formatlayıcılar (Transformers) ---

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
